apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-demo-service-monitor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
    - port: web
      path: "/actuator/prometheus"
      interval: 5s