apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
    - name: web
      protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - name: db
      protocol: TCP
      port: 5432
