{
 "title": "My Throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DEMO Latency  (Response time of 50%, 95%, 99% and MAX of requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{service=\"demo\", uri=~\"/api.*\"}[1m])) by (method,uri,le))",
     "legendFormat": "MAX: {{method}}-{{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{service=\"demo\", uri=~\"/api.*\"}[1m])) by (method,uri,le))",
     "legendFormat": "99%: {{method}}-{{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{service=\"demo\", uri=~\"/api.*\"}[1m])) by (method,uri,le))",
     "legendFormat": "95%: {{method}}-{{uri}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{service=\"demo\", uri=~\"/api.*\"}[1m])) by (method,uri,le))",
     "legendFormat": "50%: {{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "NGINX Latency  (Response time of 50%, 95%, 99% and MAX of requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*\"}[2m])) by (le))",
     "legendFormat": "MAX"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*\"}[2m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*\"}[2m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*\"}[2m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "DEMO Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(uri, method) (rate(http_server_requests_seconds_count{service=\"demo\", uri=~\"/api.*\"}[1m]))",
     "legendFormat": "{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "NGINX Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\".*\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DEMO Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"demo\", status=~\"[4-5].*\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{service=\"nginx-ingress-nginx-controller-metrics\",status=~\"[4-5].*\"}[1m])) by (ingress) ",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}