apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  namespace: {{ .Values.namespace }}
data:
#  database_host                 : "db-service.{{ .Values.namespace }}.svc.cluster.local"
  database_host                                 : "db-service"
  database_name                                 : "postgres"
  host_auth_method                              : "md5"
  pgbouncer_database                            : "*"
  pgbouncer_auth_user                           : "postgres"
  postgresql_host                               : "localhost"
  ignore_startup_parameters                     : "extra_float_digits"
  spring_jpa_show-sql                           : "true"
  spring_jpa_hibernate_ddl-auto                 : "update"
  management_endpoints_web_exposure_include     : "health,info,prometheus"
  management_metrics_export_prometheus_enabled  : "true"