apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: demo
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
