apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{ .Values.container.db.image }}
          args: ["-c", "cluster_name=main", "-c", "password_encryption=md5", "-c", "wal_level=logical", "-c", "log_directory=pg_log", "-c", "log_filename=%u_%a.log", "-c", "logging_collector=on", "-c", "wal_log_hints=on"]
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name  : demo-configmap
                  key   : database_name
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  name  : demo-configmap
                  key   : host_auth_method
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name  : demo-secret
                  key   : username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name  : demo-secret
                  key   : password
